spring:
    data:
        mongodb:
            username: root
            password: root
            host: localhost
            port: 27017
            database: chat_app
            authentication-database: admin
            auto-index-creation: true
server:
    port: 8088
jwt:
  secret: your-super-long-secret-key-which-should-be-64-bytes-for-HS512
  expiration: 86400000  # 1 day