spring:
    data:
        mongodb:
            username: root
            password: root
            host: localhost
            port: 27017
            database: chat_app
            authentication-database: admin
            auto-index-creation: true

server:
    port: 8088